[mail function]
; For Windows only.
SMTP = smtp.livemail.co.uk
smtp_port = 25
	
; For Unix only. You may use the same settings as for Windows.
sendmail_path = "/usr/sbin/sendmail -t -i"

; Common settings
sendmail_from = no-reply@musica11y.net
